#!/usr/bin/env python3
"""Arena maps: src/arenas/arena_maps.txt -> build/ArenaMaps.event.

Each arena map is a rectangle cut from a vanilla FE8 chapter map. The map layer is read from the
clean ROM (LZ77, via the chapter data table and the chapter asset table), cut, re-encoded (LZ77,
literal blocks only) and installed in the asset table slot named by the manifest. The arena keeps
the source chapter's tileset, palette, tile config and tile animations (src/arenas/arenas.c points
at them through its own copy of the chapter data).

    py -3 scripts/arenas.py      prints each arena's size and terrain grid (for checking by eye)
"""
from __future__ import annotations

import struct
import sys
from dataclasses import dataclass
from pathlib import Path

CHAPTER_TABLE = 0x8B0890        # gChapterDataTable (0x94 bytes per chapter)
CHAPTER_SIZE = 0x94
ASSET_TABLE = 0x8B363C          # gChapterDataAssetTable (pointers)


class ArenaError(Exception):
    pass


@dataclass
class ArenaMap:
    number: int
    name: str
    chapter: int
    x: int
    y: int
    w: int
    h: int
    asset: int
    blob: bytes = b""           # LZ77 map to install (empty: the vanilla asset is kept)


def lz77_decode(d: bytes, off: int) -> bytes:
    if d[off] != 0x10:
        raise ArenaError(f"no LZ77 data at {off:#x}")
    size = d[off + 1] | d[off + 2] << 8 | d[off + 3] << 16
    out = bytearray()
    i = off + 4
    while len(out) < size:
        flags = d[i]
        i += 1
        for bit in range(7, -1, -1):
            if len(out) >= size:
                break
            if flags >> bit & 1:
                b0, b1 = d[i], d[i + 1]
                i += 2
                disp = ((b0 & 0xF) << 8 | b1) + 1
                for _ in range((b0 >> 4) + 3):
                    out.append(out[-disp])
            else:
                out.append(d[i])
                i += 1
    return bytes(out)


def lz77_literal(data: bytes) -> bytes:
    """Valid LZ77 (type 0x10) using literal blocks only: small maps, no need to compress."""
    out = bytearray([0x10, len(data) & 0xFF, len(data) >> 8 & 0xFF, len(data) >> 16 & 0xFF])
    for i in range(0, len(data), 8):
        out.append(0)
        out += data[i:i + 8]
    while len(out) % 4:
        out.append(0)
    return bytes(out)


def asset_offset(rom: bytes, index: int) -> int:
    ptr = struct.unpack_from("<I", rom, ASSET_TABLE + 4 * index)[0]
    if not 0x08000000 <= ptr < 0x0A000000:
        raise ArenaError(f"asset {index:#x} is not a ROM pointer ({ptr:#x})")
    return ptr - 0x08000000


def chapter_map_index(rom: bytes, chapter: int) -> int:
    return rom[CHAPTER_TABLE + chapter * CHAPTER_SIZE + 0x08]


def cut(rom: bytes, a: ArenaMap) -> bytes:
    src = lz77_decode(rom, asset_offset(rom, chapter_map_index(rom, a.chapter)))
    sw, sh = src[0], src[1]
    if a.x + a.w > sw or a.y + a.h > sh or a.w < 15 or a.h < 10:
        raise ArenaError(f"arena {a.name}: {a.w}x{a.h} at ({a.x},{a.y}) does not fit chapter "
                         f"{a.chapter:#x}'s {sw}x{sh} map (arenas are at least 15x10)")
    out = bytearray([a.w, a.h])
    for yy in range(a.h):
        row = 2 + 2 * ((a.y + yy) * sw + a.x)
        out += src[row:row + 2 * a.w]
    return bytes(out)


def parse(manifest: Path) -> list[ArenaMap]:
    arenas = []
    for n, line in enumerate(manifest.read_text(encoding="utf-8").splitlines(), 1):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        f = line.split()
        if len(f) != 8:
            raise ArenaError(f"{manifest.name}:{n}: expected 8 fields, got {len(f)}")
        a = ArenaMap(int(f[0]), f[1], *(int(v, 0) for v in f[2:]))
        if a.number != len(arenas):
            raise ArenaError(f"{manifest.name}:{n}: arena numbers must be 0, 1, 2, ... in order")
        arenas.append(a)
    return arenas


def compile_all(manifest: Path, rom: bytes, gen: Path) -> list[ArenaMap]:
    arenas = parse(manifest)
    used = {}
    lines = ["// Generated by scripts/arenas.py from src/arenas/arena_maps.txt. Do not edit.", ""]
    for a in arenas:
        if a.asset == chapter_map_index(rom, a.chapter):
            if (a.x, a.y) != (0, 0):
                raise ArenaError(f"arena {a.name}: a cut map needs its own asset slot")
            continue                                        # the whole vanilla map, as it is
        if a.asset in used:
            raise ArenaError(f"arenas {used[a.asset]} and {a.name} share asset {a.asset:#x}")
        used[a.asset] = a.name
        a.blob = lz77_literal(cut(rom, a))
        lines += ["PUSH", f"ORG {ASSET_TABLE + 4 * a.asset:#x}", f"POIN ColArenaMap_{a.name}", "POP",
                  "ALIGN 4", f"ColArenaMap_{a.name}:",
                  *("BYTE " + " ".join(f"${b:02X}" for b in a.blob[i:i + 16]) for i in range(0, len(a.blob), 16)),
                  ""]
    gen.mkdir(exist_ok=True)
    (gen / "ArenaMaps.event").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return arenas


def verify_rom(arenas: list[ArenaMap], data: bytes) -> list[str]:
    problems = []
    for a in arenas:
        if not a.blob:
            continue
        off = asset_offset(data, a.asset)
        if data[off:off + len(a.blob)] != a.blob:
            problems.append(f"arena {a.name}: asset {a.asset:#x} does not point at its map")
    return problems


if __name__ == "__main__":
    root = Path(__file__).resolve().parent.parent
    rom = (root / "FE8_clean.gba").read_bytes()
    for a in parse(root / "src" / "arenas" / "arena_maps.txt"):
        m = cut(rom, a)
        print(f"{a.number} {a.name}: {m[0]}x{m[1]} from chapter {a.chapter:#x} -> asset {a.asset:#x}")
    sys.exit(0)
