#!/usr/bin/env python3
"""Portrait pipeline: src/graphics/portraits/*.png -> build/Portraits.event (scripts/build.py).

For each line of src/graphics/portraits/Portraits.txt:
  1. check the sheet (128x112, <= 16 colours) and compare the manifest's mouth/eye coordinates
     with the ones the sheet suggests (mugtool; a mismatch is a warning);
  2. run PortraitFormatter.exe -> build/portraits/<name>.dmp and validate the result
     (PortraitFormatter prints errors on stdout with exit code 0);
  3. emit `#incbin` + a portrait-table entry into build/Portraits.event.
After assembly, verify_rom() checks every portrait-table entry against the data.
Ported from The Severed Star's pipeline (same tool, same checks).
"""
from __future__ import annotations

import struct
import subprocess
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

import mugtool

PORTRAIT_TABLE = 0x8ACBC4                  # ROM offset of vanilla FE8U's portrait table (not repointed)
PORTRAIT_ENTRY = 0x1C
DMP_HEADER = b"\x00\x04\x10\x00"           # same as vanilla portrait graphics
MINI, PALETTE, MOUTH = 0x1624, 0x1604, 0x1004


class PortraitError(Exception):
    pass


@dataclass
class Portrait:
    portrait_id: int
    png: Path
    mouth: tuple[int, int]
    eyes: tuple[int, int]
    data: bytes = b""

    @property
    def name(self) -> str:
        return "".join(c if c.isalnum() else "_" for c in self.png.stem)

    @property
    def label(self) -> str:
        return f"Col_Portrait_{self.name}"


def read_manifest(manifest: Path) -> list[Portrait]:
    items, seen = [], {}
    if not manifest.is_file():
        return items
    for n, raw in enumerate(manifest.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 6:
            raise PortraitError(f"{manifest}:{n}: expected 'ID FILE.png MX MY EX EY', got {raw!r}")
        try:
            pid = int(parts[0], 0)
            mx, my, ex, ey = (int(v) for v in parts[2:])
        except ValueError:
            raise PortraitError(f"{manifest}:{n}: bad number in {raw!r}")
        if pid in seen:
            raise PortraitError(f"{manifest}:{n}: portrait {pid:#x} already set on line {seen[pid]}")
        seen[pid] = n
        items.append(Portrait(pid, manifest.parent / parts[1], (mx, my), (ex, ey)))
    return items


def compile_all(manifest: Path, formatter: Path, out_dir: Path) -> tuple[list[Portrait], list[str]]:
    """Returns (portraits, warnings)."""
    portraits = read_manifest(manifest)
    warnings: list[str] = []
    dmp_dir = out_dir / "portraits"
    dmp_dir.mkdir(parents=True, exist_ok=True)
    for p in portraits:
        if not p.png.is_file():
            raise PortraitError(f"{p.png}: file not found")
        try:
            info = mugtool.analyse(p.png)
        except ValueError as e:
            raise PortraitError(str(e))
        if info["colours"] > 16:
            raise PortraitError(f"{p.png}: {info['colours']} colours; GBA portraits allow at most 16")
        mouth = Counter((tx, ty) for _, tx, ty in info["mouth"]).most_common(1)[0][0]
        eyes = Counter((tx, ty) for _, tx, ty in info["eyes"]).most_common(1)[0][0]
        if (mouth, eyes) != (p.mouth, p.eyes):
            warnings.append(f"{p.png.name}: manifest mouth {p.mouth} eyes {p.eyes}, "
                            f"sheet suggests mouth {mouth} eyes {eyes}")

        dmp = dmp_dir / f"{p.name}.dmp"
        dmp.unlink(missing_ok=True)
        r = subprocess.run([str(formatter), str(p.png), "-o", str(dmp)],
                           capture_output=True, text=True, errors="replace")
        out = (r.stdout + r.stderr).strip()
        if r.returncode != 0 or "ERROR" in out.upper() or not dmp.is_file():
            raise PortraitError(f"PortraitFormatter failed on {p.png.name}: {out or 'no output file'}")
        data = dmp.read_bytes()
        if len(data) < MINI + 4 or data[:4] != DMP_HEADER or data[MINI] != 0x10:
            raise PortraitError(f"{dmp.name}: unexpected PortraitFormatter output layout")
        p.data = data

    lines = ["// GENERATED by scripts/portraits.py from src/graphics/portraits/ - do not edit.\n",
             f"#define ColPortraitTable {PORTRAIT_TABLE:#x}\n#define ColPortraitEntrySize {PORTRAIT_ENTRY:#x}\n"]
    for p in portraits:
        lines.append(f"\n// {p.png.name} -> portrait {p.portrait_id:#x}\nALIGN 4\n{p.label}:\n")
        lines.append(f'#incbin "portraits/{p.name}.dmp"\n')
        lines.append(f"PUSH\nORG ColPortraitTable + {p.portrait_id:#x} * ColPortraitEntrySize\n"
                     f"POIN {p.label}\nPOIN {p.label} + {MINI:#x}\nPOIN {p.label} + {PALETTE:#x}\n"
                     f"POIN {p.label} + {MOUTH:#x}\nWORD 0\n"
                     f"BYTE {p.mouth[0]} {p.mouth[1]} {p.eyes[0]} {p.eyes[1]}\nWORD 1\nPOP\n")
    lines.append("\nALIGN 4\n")
    (out_dir / "Portraits.event").write_text("".join(lines), encoding="utf-8")
    return portraits, warnings


def verify_rom(portraits: list[Portrait], rom: bytes) -> list[str]:
    problems = []
    for p in portraits:
        e = PORTRAIT_TABLE + p.portrait_id * PORTRAIT_ENTRY
        main, mini, pal, mouth, zero = struct.unpack_from("<5I", rom, e)
        coords = tuple(rom[e + 20:e + 24])
        base = main - 0x08000000
        if not 0 <= base < len(rom) or rom[base:base + len(p.data)] != p.data:
            problems.append(f"{p.png.name}: portrait {p.portrait_id:#x} graphics pointer {main:#x} does not hold its data")
            continue
        if (mini - main, pal - main, mouth - main, zero) != (MINI, PALETTE, MOUTH, 0):
            problems.append(f"{p.png.name}: portrait {p.portrait_id:#x} sub-pointers are wrong")
        if coords != (*p.mouth, *p.eyes):
            problems.append(f"{p.png.name}: portrait {p.portrait_id:#x} coordinates {coords} != manifest")
    return problems
